### PR TITLE
Added unlicense to the repo

### PR DESCRIPTION
**Pull request by geekthattweaks**
Per issue #4 adding the unlicense to the repo.

### CODE REVIEW

**Review by pythoninthegrass — APPROVED** [review]
lgtm
(lgtm)

bc mobile github is trash

**Comment by geekthattweaks** [comment]
image

**Comment by pythoninthegrass** [comment]
Turns out it's automatic if the repo is already has the "hacktoberfest" label.

See: https://hacktoberfest.com/participation/#maintainers
________________________________

**Comment by geekthattweaks** [comment]
I didn't see it as a topic or in my list of PR on hacktoberfest.com but maybe I'm missing something.

Thanks for the quick reply!

**Comment by geekthattweaks** [comment]
@pythoninthegrass this repo seems to use the tag
image

**Comment by pythoninthegrass** [comment]
Fixed! It's due to the whole repo not being advertised with the [hacktoberfest topic](https://hacktoberfest.com/participation/#maintainers).

**Pull request merged**
